2025/06/24 13:47:56 [error] 11#11: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.86.31, server: localhost, request: "GET /api/message HTTP/1.1", upstream: "http://127.0.0.1:1314/api/message", host: "192.168.86.183:1313", referrer: "http://192.168.86.183:1313/"
2025/06/24 13:47:56 [error] 11#11: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.86.31, server: localhost, request: "GET /api/message HTTP/1.1", upstream: "http://127.0.0.1:1314/api/message", host: "192.168.86.183:1313", referrer: "http://192.168.86.183:1313/"
2025/06/24 13:47:59 [error] 11#11: *2 no live upstreams while connecting to upstream, client: 192.168.86.31, server: localhost, request: "GET /api/message HTTP/1.1", upstream: "http://localhost/api/message", host: "192.168.86.183:1313", referrer: "http://192.168.86.183:1313/"
2025/06/24 13:48:01 [error] 11#11: *2 no live upstreams while connecting to upstream, client: 192.168.86.31, server: localhost, request: "GET /api/message HTTP/1.1", upstream: "http://localhost/api/message", host: "192.168.86.183:1313", referrer: "http://192.168.86.183:1313/"
2025/06/24 13:48:02 [error] 11#11: *2 no live upstreams while connecting to upstream, client: 192.168.86.31, server: localhost, request: "GET /api/message HTTP/1.1", upstream: "http://localhost/api/message", host: "192.168.86.183:1313", referrer: "http://192.168.86.183:1313/"
2025/06/24 13:48:02 [error] 11#11: *2 no live upstreams while connecting to upstream, client: 192.168.86.31, server: localhost, request: "GET /api/message HTTP/1.1", upstream: "http://localhost/api/message", host: "192.168.86.183:1313", referrer: "http://192.168.86.183:1313/"
